apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"version":"v1","zone":"prod"},"name":"nginx","namespace":"default"},"spec":{"containers":[{"image":"hadiazb/nginx:v1","name":"nginx"}]}}
  creationTimestamp: "2021-07-15T22:42:18Z"
  labels:
    version: v1
    zone: prod
  name: nginx
  namespace: default
  resourceVersion: "44154"
  uid: 055fac71-a324-4a4a-8ec0-96d4f5f1cbc4
spec:
  containers:
  - image: hadiazb/nginx:v1
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wxftl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-wxftl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-07-15T22:42:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-07-15T22:44:01Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-07-15T22:44:01Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-07-15T22:42:18Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://59f186a321308edab4c22ccbfb55478c7bf718cac1de3c0bfec4357e15855d97
    image: hadiazb/nginx:v1
    imageID: docker-pullable://hadiazb/nginx@sha256:fafb29c8b313dd037f1e8f0f2f3bf45dde07bb550d0d10ccbec20fb5734414cb
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-07-15T22:44:01Z"
  hostIP: 192.168.58.2
  phase: Running
  podIP: 172.17.0.6
  podIPs:
  - ip: 172.17.0.6
  qosClass: BestEffort
  startTime: "2021-07-15T22:42:18Z"
